name: Golu-woc Docker Compacket

on:
  push:
    branches: [ "woc" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Version With Timestamp
      id: set_version
      run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build The Docker Image
      run: docker build . --file docker/Dockerfile --tag goolucky/woc:${{ env.VERSION }}

    - name: Tag Image As Latest
      run: docker tag goolucky/woc:${{ env.VERSION }} goolucky/woc:latest

    - name: Push Docker Image With Timestamp Tag
      run: docker push goolucky/woc:${{ env.VERSION }}

    - name: Push Docker Image With Latest Tag
      run: docker push goolucky/woc:latest
